Add compiled sources in JAR in scalapb-maven-example
jbkt/scalapb-maven pull request #4
Opened 2018-09-14 09:47 UTC by norbjd

Hi,

I've noticed that the `scalapb-maven-example` did not compile generated sources, so the JAR generated during `package` phase is empty:

```
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ scalapb-maven-example ---
[WARNING] JAR will be empty - no content was marked for inclusion!
```

I've updated the example to make a complete example of using the plugin (not just generating Scala sources, but **also compiling them**). This will help beginners to use the plugin I think.

2018-09-18 14:35 UTC, jbkt requested changes

2018-09-18 14:35 UTC, jbkt commented on scalapb-maven-example/pom.xml
> +    <scala.major.minor.version>2.11</scala.major.minor.version>
Should use versions from the parent pom.

2018-09-18 14:35 UTC, jbkt commented on scalapb-maven-example/pom.xml
> +      <version>${scala.version}</version>
Version already in dependency management.

2018-09-19 07:55 UTC, norbjd commented
Thanks for the review, just fixed that :smile:

2018-09-19 08:32 UTC, merged